# Classifying Penguins with Keras

In [86]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn import preprocessing
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score, roc_curve

In [87]:
! pip install palmerpenguins
from palmerpenguins import load_penguins
penguins = load_penguins()
penguins.head()

Requirement already satisfied: palmerpenguins in C:\Users\karis\anaconda3\Lib\site-packages (0.1.6)
Requirement already satisfied: pandas in C:\Users\karis\anaconda3\Lib\site-packages (from palmerpenguins) (2.2.3)
Requirement already satisfied: numpy in C:\Users\karis\anaconda3\Lib\site-packages (from palmerpenguins) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\karis\AppData\Local\Programs\Positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from pandas->palmerpenguins) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\karis\anaconda3\Lib\site-packages (from pandas->palmerpenguins) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\karis\anaconda3\Lib\site-packages (from pandas->palmerpenguins) (2025.2)
Requirement already satisfied: six>=1.5 in c:\Users\karis\AppData\Local\Programs\Positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from python-dateutil>=2.8.2->pandas->palmerpenguins) (1.17.0)

  species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g     sex  year
0  Adelie  Torgersen            39.1           18.7              181.0       3750.0    male  2007
1  Adelie  Torgersen            39.5           17.4              186.0       3800.0  female  2007
2  Adelie  Torgersen            40.3           18.0              195.0       3250.0  female  2007
3  Adelie  Torgersen             NaN            NaN                NaN          NaN     NaN  2007
4  Adelie  Torgersen            36.7           19.3              193.0       3450.0  female  2007

In [88]:
#drop nan rows
penguins = penguins.dropna()
penguins.shape

(333, 8)

In [89]:
#shuffle the data
penguins = penguins.sample(frac=1, random_state = 42).reset_index(drop=True)

In [90]:
penguins_x = pd.concat([penguins[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm']], pd.get_dummies(penguins['sex'])], axis = 1)
# penguins_x = penguins_x[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'female', 'male']]
penguins_x

     body_mass_g  bill_length_mm  bill_depth_mm  flipper_length_mm  female   male
0         3250.0            39.5           16.7              178.0    True  False
1         3675.0            50.9           17.9              196.0    True  False
2         4000.0            42.1           19.1              195.0   False   True
3         4850.0            46.6           14.2              210.0    True  False
4         4050.0            41.1           18.2              192.0   False   True
..           ...             ...            ...                ...     ...    ...
328       4750.0            49.6           15.0              216.0   False   True
329       3900.0            37.2           19.4              184.0   False   True
330       3200.0            39.7           17.7              193.0    True  False
331       3950.0            45.2           17.8              198.0    True  False
332       3175.0            38.1           17.0              181.0    True  False

[333 rows x 6 columns]

In [91]:
x = penguins_x.values
min_max_scaler = preprocessing.MinMaxScaler()
scaled_penguins_x = pd.DataFrame(min_max_scaler.fit_transform(x), columns=penguins_x.columns)
scaled_penguins_x

     body_mass_g  bill_length_mm  bill_depth_mm  flipper_length_mm  female  male
0       0.152778        0.269091       0.428571           0.101695     1.0   0.0
1       0.270833        0.683636       0.571429           0.406780     1.0   0.0
2       0.361111        0.363636       0.714286           0.389831     0.0   1.0
3       0.597222        0.527273       0.130952           0.644068     1.0   0.0
4       0.375000        0.327273       0.607143           0.338983     0.0   1.0
..           ...             ...            ...                ...     ...   ...
328     0.569444        0.636364       0.226190           0.745763     0.0   1.0
329     0.333333        0.185455       0.750000           0.203390     0.0   1.0
330     0.138889        0.276364       0.547619           0.355932     1.0   0.0
331     0.347222        0.476364       0.559524           0.440678     1.0   0.0
332     0.131944        0.218182       0.464286           0.152542     1.0   0.0

[333 rows x 6 columns]

In [92]:
penguins_y = penguins['species']
print(penguins_y)
penguins_y = penguins_y.astype('category').cat.codes.to_numpy()
penguins_y

0         Adelie
1      Chinstrap
2         Adelie
3         Gentoo
4         Adelie
         ...
328       Gentoo
329       Adelie
330       Adelie
331    Chinstrap
332       Adelie
Name: species, Length: 333, dtype: object

array([0, 1, 0, 2, 0, 1, 1, 2, 2, 2, 0, 0, 1, 0, 1, 0, 0, 2, 0, 1, 0, 0, 1, 2, 0, 0, 2, 1, 2, 1, 2, 1, 0, 0, 1, 1, 2, 2, 0, 0, 0,
       0, 2, 2, 0, 0, 1, 0, 0, 1, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 0, 1, 0, 2, 0, 1, 0, 0, 2, 1, 2, 2, 0, 0, 0, 2, 0, 0,
       2, 0, 1, 2, 0, 1, 2, 2, 2, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 2, 0, 2, 2, 0, 2, 0, 1, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 1,
       0, 0, 1, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 1, 2, 1, 2, 1, 2, 2, 2, 2, 0, 0, 2, 2, 2, 0, 2, 2, 0, 1, 1, 1,
       2, 2, 2, 2, 2, 0, 0, 2, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 2, 1, 0, 2, 2, 0, 1, 0, 1, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 0, 1, 0, 0,
       2, 2, 2, 0, 0, 0, 2, 2, 0, 0, 1, 0, 2, 0, 1, 1, 1, 0, 2, 1, 2, 2, 0, 2, 0, 0, 2, 0, 2, 0, 2, 1, 0, 1, 2, 1, 0, 2, 2, 2, 0,
       0, 0, 2, 2, 2, 1, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 1, 1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0, 2,
       0, 2, 0, 0, 2, 2, 0, 0, 1, 2, 1, 0, 1, 2, 0, 0, 2, 2, 1, 2, 2, 0, 0, 2, 2, 0, 2, 1, 2, 1, 2, 1, 2, 0, 2, 0, 0, 2, 0, 1, 0,
       2, 0, 0, 1, 0], dtype=int8)

In [93]:
#construct the model
inputs = keras.Input(shape=(6,))
x = layers.Dense(7, activation = 'relu')(inputs)
x = layers.Dense(5, activation = 'relu')(x)
x = layers.Dense(3, activation = 'relu')(x)
#make sure the model activation is right for 3 categories, not sigmoid
outputs = layers.Dense(3, activation='softmax')(x)
model = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model")

In [94]:
model.summary()

Model: "penguin_model"
┌──────────────────────────────────────┬─────────────────────────────┬─────────────────┐
│ Layer (type)                         │ Output Shape                │         Param # │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ input_layer_6 (InputLayer)           │ (None, 6)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_24 (Dense)                     │ (None, 7)                   │              49 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_25 (Dense)                     │ (None, 5)                   │              40 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_26 (Dense)                     │ (None, 3)                   │              18 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_27 (Dense)                     │ (None, 3)                   │              12 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘
 Total params: 119 (476.00 B)
 Trainable params: 119 (476.00 B)
 Non-trainable params: 0 (0.00 B)

In [95]:
#don't have the right library to run, don't worry about it
keras.utils.plot_model(model, show_shapes = True)

You must install pydot (`pip install pydot`) for `plot_model` to work.

In [96]:
#issue with this code, nan fields in penguins datasets, so need to add code cell to get rid of NAN's 
#but for now dropping rows with nan's, see above
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)
#make sure to shuffle the data
history = model.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs=100, validation_split=0.1)

scores = model.evaluate(scaled_penguins_x, penguins_y, verbose=2)

Epoch 1/100

C:\Users\karis\anaconda3\Lib\site-packages\keras\src\backend\tensorflow\nn.py:1216: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.3512 - loss: 1.0799 - val_accuracy: 0.4118 - val_loss: 1.0628
Epoch 2/100
1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.3906 - loss: 1.0597

C:\Users\karis\anaconda3\Lib\site-packages\keras\src\backend\tensorflow\nn.py:1216: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.3512 - loss: 1.0712 - val_accuracy: 0.4118 - val_loss: 1.0571
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.3512 - loss: 1.0653 - val_accuracy: 0.4118 - val_loss: 1.0523
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.3545 - loss: 1.0605 - val_accuracy: 0.4118 - val_loss: 1.0482
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.3645 - loss: 1.0563 - val_accuracy: 0.4118 - val_loss: 1.0442
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.3645 - loss: 1.0519 - val_accuracy: 0.4118 - val_loss: 1.0402
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.3712 - loss: 1.0478 - val_accuracy: 0.4706 - val_loss: 1.0366
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.3846 - loss: 1.0436 - val_accuracy: 0.4706 - val_loss: 1.0328
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.3946 - loss: 1.0394 - val_accuracy: 0.5000 - val_loss: 1.0291
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.4047 - loss: 1.0352 - val_accuracy: 0.5000 - val_loss: 1.0257
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.4214 - loss: 1.0309 - val_accuracy: 0.5000 - val_loss: 1.0217
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.4247 - loss: 1.0265 - val_accuracy: 0.5000 - val_loss: 1.0180
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.4649 - loss: 1.0223 - val_accuracy: 0.5294 - val_loss: 1.0141
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.4682 - loss: 1.0178 - val_accuracy: 0.5294 - val_loss: 1.0097
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.4783 - loss: 1.0130 - val_accuracy: 0.5588 - val_loss: 1.0052
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.4950 - loss: 1.0083 - val_accuracy: 0.5882 - val_loss: 1.0013
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.5050 - loss: 1.0040 - val_accuracy: 0.5882 - val_loss: 0.9975
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.5184 - loss: 0.9996 - val_accuracy: 0.6765 - val_loss: 0.9936
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.5585 - loss: 0.9949 - val_accuracy: 0.6765 - val_loss: 0.9888
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.5552 - loss: 0.9903 - val_accuracy: 0.6765 - val_loss: 0.9844
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5886 - loss: 0.9851 - val_accuracy: 0.6765 - val_loss: 0.9798
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6020 - loss: 0.9799 - val_accuracy: 0.6765 - val_loss: 0.9746
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6254 - loss: 0.9744 - val_accuracy: 0.7059 - val_loss: 0.9689
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6321 - loss: 0.9685 - val_accuracy: 0.7059 - val_loss: 0.9632
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6455 - loss: 0.9629 - val_accuracy: 0.7059 - val_loss: 0.9580
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6756 - loss: 0.9568 - val_accuracy: 0.7353 - val_loss: 0.9523
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6957 - loss: 0.9507 - val_accuracy: 0.7353 - val_loss: 0.9469
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7124 - loss: 0.9450 - val_accuracy: 0.7647 - val_loss: 0.9411
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7191 - loss: 0.9392 - val_accuracy: 0.7941 - val_loss: 0.9352
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.7258 - loss: 0.9333 - val_accuracy: 0.7941 - val_loss: 0.9294
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7291 - loss: 0.9276 - val_accuracy: 0.7941 - val_loss: 0.9242
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7559 - loss: 0.9218 - val_accuracy: 0.7941 - val_loss: 0.9185
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7592 - loss: 0.9161 - val_accuracy: 0.7941 - val_loss: 0.9131
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7625 - loss: 0.9106 - val_accuracy: 0.7941 - val_loss: 0.9080
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7659 - loss: 0.9046 - val_accuracy: 0.7941 - val_loss: 0.9018
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7659 - loss: 0.8988 - val_accuracy: 0.7941 - val_loss: 0.8959
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7659 - loss: 0.8927 - val_accuracy: 0.7941 - val_loss: 0.8898
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7659 - loss: 0.8869 - val_accuracy: 0.7941 - val_loss: 0.8844
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7726 - loss: 0.8806 - val_accuracy: 0.7941 - val_loss: 0.8783
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7726 - loss: 0.8745 - val_accuracy: 0.7941 - val_loss: 0.8725
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7759 - loss: 0.8684 - val_accuracy: 0.7941 - val_loss: 0.8662
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7793 - loss: 0.8621 - val_accuracy: 0.7941 - val_loss: 0.8601
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7826 - loss: 0.8555 - val_accuracy: 0.7941 - val_loss: 0.8537
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7860 - loss: 0.8491 - val_accuracy: 0.7941 - val_loss: 0.8467
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7860 - loss: 0.8426 - val_accuracy: 0.7941 - val_loss: 0.8405
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7860 - loss: 0.8360 - val_accuracy: 0.7941 - val_loss: 0.8342
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7860 - loss: 0.8296 - val_accuracy: 0.7941 - val_loss: 0.8273
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7860 - loss: 0.8229 - val_accuracy: 0.7941 - val_loss: 0.8205
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7860 - loss: 0.8163 - val_accuracy: 0.7941 - val_loss: 0.8142
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7960 - loss: 0.8097 - val_accuracy: 0.7941 - val_loss: 0.8072
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7960 - loss: 0.8031 - val_accuracy: 0.7941 - val_loss: 0.8009
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7960 - loss: 0.7963 - val_accuracy: 0.7941 - val_loss: 0.7932
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7960 - loss: 0.7897 - val_accuracy: 0.7941 - val_loss: 0.7861
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7960 - loss: 0.7829 - val_accuracy: 0.7941 - val_loss: 0.7797
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7960 - loss: 0.7768 - val_accuracy: 0.7941 - val_loss: 0.7731
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7960 - loss: 0.7698 - val_accuracy: 0.7941 - val_loss: 0.7665
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7960 - loss: 0.7633 - val_accuracy: 0.7941 - val_loss: 0.7602
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7960 - loss: 0.7566 - val_accuracy: 0.7941 - val_loss: 0.7530
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7960 - loss: 0.7501 - val_accuracy: 0.7941 - val_loss: 0.7463
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7960 - loss: 0.7434 - val_accuracy: 0.7941 - val_loss: 0.7399
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7960 - loss: 0.7368 - val_accuracy: 0.7941 - val_loss: 0.7329
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7960 - loss: 0.7302 - val_accuracy: 0.7941 - val_loss: 0.7262
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7960 - loss: 0.7234 - val_accuracy: 0.7941 - val_loss: 0.7183
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7960 - loss: 0.7165 - val_accuracy: 0.7941 - val_loss: 0.7119
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7960 - loss: 0.7096 - val_accuracy: 0.7941 - val_loss: 0.7043
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7960 - loss: 0.7026 - val_accuracy: 0.7941 - val_loss: 0.6964
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7960 - loss: 0.6952 - val_accuracy: 0.7941 - val_loss: 0.6895
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7960 - loss: 0.6881 - val_accuracy: 0.7941 - val_loss: 0.6819
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7960 - loss: 0.6809 - val_accuracy: 0.7941 - val_loss: 0.6741
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7960 - loss: 0.6737 - val_accuracy: 0.7941 - val_loss: 0.6676
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7960 - loss: 0.6666 - val_accuracy: 0.7941 - val_loss: 0.6601
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7960 - loss: 0.6596 - val_accuracy: 0.7941 - val_loss: 0.6521
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7960 - loss: 0.6523 - val_accuracy: 0.7941 - val_loss: 0.6446
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7960 - loss: 0.6451 - val_accuracy: 0.7941 - val_loss: 0.6369
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7960 - loss: 0.6381 - val_accuracy: 0.7941 - val_loss: 0.6299
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7960 - loss: 0.6308 - val_accuracy: 0.7941 - val_loss: 0.6223
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7960 - loss: 0.6236 - val_accuracy: 0.7941 - val_loss: 0.6153
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7960 - loss: 0.6164 - val_accuracy: 0.7941 - val_loss: 0.6076
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7960 - loss: 0.6093 - val_accuracy: 0.7941 - val_loss: 0.6001
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7960 - loss: 0.6024 - val_accuracy: 0.7941 - val_loss: 0.5927
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7960 - loss: 0.5953 - val_accuracy: 0.7941 - val_loss: 0.5856
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7960 - loss: 0.5887 - val_accuracy: 0.7941 - val_loss: 0.5792
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7960 - loss: 0.5820 - val_accuracy: 0.7941 - val_loss: 0.5726
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7960 - loss: 0.5753 - val_accuracy: 0.7941 - val_loss: 0.5667
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7960 - loss: 0.5687 - val_accuracy: 0.7941 - val_loss: 0.5593
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7960 - loss: 0.5623 - val_accuracy: 0.7941 - val_loss: 0.5527
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7960 - loss: 0.5562 - val_accuracy: 0.7941 - val_loss: 0.5469
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7960 - loss: 0.5499 - val_accuracy: 0.7941 - val_loss: 0.5404
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7960 - loss: 0.5439 - val_accuracy: 0.7941 - val_loss: 0.5340
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7960 - loss: 0.5385 - val_accuracy: 0.7941 - val_loss: 0.5286
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7960 - loss: 0.5324 - val_accuracy: 0.7941 - val_loss: 0.5229
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7960 - loss: 0.5272 - val_accuracy: 0.7941 - val_loss: 0.5180
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7960 - loss: 0.5219 - val_accuracy: 0.7941 - val_loss: 0.5119
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7960 - loss: 0.5167 - val_accuracy: 0.7941 - val_loss: 0.5065
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7960 - loss: 0.5115 - val_accuracy: 0.7941 - val_loss: 0.5012
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7960 - loss: 0.5065 - val_accuracy: 0.7941 - val_loss: 0.4952
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7960 - loss: 0.5014 - val_accuracy: 0.7941 - val_loss: 0.4900
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7960 - loss: 0.4967 - val_accuracy: 0.7941 - val_loss: 0.4855
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7960 - loss: 0.4918 - val_accuracy: 0.7941 - val_loss: 0.4800
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7960 - loss: 0.4874 - val_accuracy: 0.7941 - val_loss: 0.4742
11/11 - 0s - 6ms/step - accuracy: 0.7958 - loss: 0.4833

In [97]:
model_logit_false = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model_scaled")

model_logit_false.compile(
    #don't recalculate the classes, already told the model the info it needs with softmax
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history_logit_true = model_logit_false.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs = 100, validation_split = 0.1)

scores = model_logit_false.evaluate(scaled_penguins_x, penguins_y, verbose = 2)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 83ms/step - accuracy: 0.7960 - loss: 0.4806 - val_accuracy: 0.7941 - val_loss: 0.4647
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7960 - loss: 0.4734 - val_accuracy: 0.7941 - val_loss: 0.4586
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7960 - loss: 0.4685 - val_accuracy: 0.7941 - val_loss: 0.4533
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7960 - loss: 0.4643 - val_accuracy: 0.7941 - val_loss: 0.4490
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7960 - loss: 0.4606 - val_accuracy: 0.7941 - val_loss: 0.4452
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7960 - loss: 0.4572 - val_accuracy: 0.7941 - val_loss: 0.4408
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7960 - loss: 0.4539 - val_accuracy: 0.7941 - val_loss: 0.4378
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7960 - loss: 0.4507 - val_accuracy: 0.7941 - val_loss: 0.4345
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7960 - loss: 0.4480 - val_accuracy: 0.7941 - val_loss: 0.4306
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7960 - loss: 0.4451 - val_accuracy: 0.7941 - val_loss: 0.4275
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7960 - loss: 0.4422 - val_accuracy: 0.7941 - val_loss: 0.4238
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7960 - loss: 0.4396 - val_accuracy: 0.7941 - val_loss: 0.4204
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7960 - loss: 0.4370 - val_accuracy: 0.7941 - val_loss: 0.4167
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7960 - loss: 0.4344 - val_accuracy: 0.7941 - val_loss: 0.4131
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7960 - loss: 0.4320 - val_accuracy: 0.7941 - val_loss: 0.4104
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7960 - loss: 0.4296 - val_accuracy: 0.7941 - val_loss: 0.4066
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7960 - loss: 0.4274 - val_accuracy: 0.7941 - val_loss: 0.4038
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7960 - loss: 0.4253 - val_accuracy: 0.7941 - val_loss: 0.4003
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7960 - loss: 0.4229 - val_accuracy: 0.7941 - val_loss: 0.3971
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7960 - loss: 0.4209 - val_accuracy: 0.7941 - val_loss: 0.3944
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7960 - loss: 0.4187 - val_accuracy: 0.7941 - val_loss: 0.3918
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7960 - loss: 0.4166 - val_accuracy: 0.7941 - val_loss: 0.3885
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7960 - loss: 0.4145 - val_accuracy: 0.7941 - val_loss: 0.3858
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7960 - loss: 0.4123 - val_accuracy: 0.7941 - val_loss: 0.3832
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7960 - loss: 0.4106 - val_accuracy: 0.7941 - val_loss: 0.3804
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7960 - loss: 0.4086 - val_accuracy: 0.7941 - val_loss: 0.3774
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7960 - loss: 0.4064 - val_accuracy: 0.7941 - val_loss: 0.3738
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7960 - loss: 0.4043 - val_accuracy: 0.7941 - val_loss: 0.3708
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7960 - loss: 0.4023 - val_accuracy: 0.7941 - val_loss: 0.3674
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7960 - loss: 0.4003 - val_accuracy: 0.7941 - val_loss: 0.3643
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7960 - loss: 0.3982 - val_accuracy: 0.7941 - val_loss: 0.3613
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7960 - loss: 0.3960 - val_accuracy: 0.7941 - val_loss: 0.3581
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7960 - loss: 0.3940 - val_accuracy: 0.7941 - val_loss: 0.3547
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7993 - loss: 0.3917 - val_accuracy: 0.7941 - val_loss: 0.3516
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7993 - loss: 0.3896 - val_accuracy: 0.7941 - val_loss: 0.3495
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7993 - loss: 0.3873 - val_accuracy: 0.7941 - val_loss: 0.3460
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7993 - loss: 0.3854 - val_accuracy: 0.7941 - val_loss: 0.3429
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8027 - loss: 0.3832 - val_accuracy: 0.7941 - val_loss: 0.3399
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8060 - loss: 0.3812 - val_accuracy: 0.8235 - val_loss: 0.3359
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8060 - loss: 0.3791 - val_accuracy: 0.8235 - val_loss: 0.3326
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8094 - loss: 0.3773 - val_accuracy: 0.8529 - val_loss: 0.3286
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8094 - loss: 0.3750 - val_accuracy: 0.8529 - val_loss: 0.3250
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8094 - loss: 0.3730 - val_accuracy: 0.8529 - val_loss: 0.3220
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8161 - loss: 0.3706 - val_accuracy: 0.8529 - val_loss: 0.3189
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8127 - loss: 0.3686 - val_accuracy: 0.8529 - val_loss: 0.3151
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8294 - loss: 0.3662 - val_accuracy: 0.8529 - val_loss: 0.3126
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8227 - loss: 0.3638 - val_accuracy: 0.8529 - val_loss: 0.3080
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8328 - loss: 0.3617 - val_accuracy: 0.8529 - val_loss: 0.3046
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8294 - loss: 0.3600 - val_accuracy: 0.8529 - val_loss: 0.3016
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8328 - loss: 0.3572 - val_accuracy: 0.9118 - val_loss: 0.2978
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8361 - loss: 0.3548 - val_accuracy: 0.9118 - val_loss: 0.2946
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8328 - loss: 0.3529 - val_accuracy: 0.9118 - val_loss: 0.2905
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8462 - loss: 0.3503 - val_accuracy: 0.9118 - val_loss: 0.2877
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8428 - loss: 0.3476 - val_accuracy: 0.9118 - val_loss: 0.2830
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8462 - loss: 0.3454 - val_accuracy: 0.9118 - val_loss: 0.2801
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8462 - loss: 0.3426 - val_accuracy: 0.9118 - val_loss: 0.2766
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8462 - loss: 0.3405 - val_accuracy: 0.9412 - val_loss: 0.2713
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8562 - loss: 0.3373 - val_accuracy: 0.9412 - val_loss: 0.2682
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8562 - loss: 0.3348 - val_accuracy: 0.9412 - val_loss: 0.2639
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8562 - loss: 0.3319 - val_accuracy: 0.9412 - val_loss: 0.2612
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8562 - loss: 0.3290 - val_accuracy: 0.9412 - val_loss: 0.2560
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8629 - loss: 0.3266 - val_accuracy: 0.9412 - val_loss: 0.2542
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8629 - loss: 0.3234 - val_accuracy: 0.9412 - val_loss: 0.2507
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8629 - loss: 0.3210 - val_accuracy: 0.9412 - val_loss: 0.2467
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8629 - loss: 0.3186 - val_accuracy: 0.9412 - val_loss: 0.2423
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8763 - loss: 0.3154 - val_accuracy: 0.9412 - val_loss: 0.2395
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8696 - loss: 0.3126 - val_accuracy: 0.9412 - val_loss: 0.2347
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8763 - loss: 0.3097 - val_accuracy: 0.9412 - val_loss: 0.2319
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8662 - loss: 0.3075 - val_accuracy: 0.9412 - val_loss: 0.2288
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8763 - loss: 0.3040 - val_accuracy: 0.9412 - val_loss: 0.2246
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8763 - loss: 0.3010 - val_accuracy: 0.9412 - val_loss: 0.2217
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8696 - loss: 0.2995 - val_accuracy: 0.9412 - val_loss: 0.2188
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8796 - loss: 0.2954 - val_accuracy: 0.9412 - val_loss: 0.2158
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8763 - loss: 0.2932 - val_accuracy: 0.9412 - val_loss: 0.2117
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8829 - loss: 0.2899 - val_accuracy: 0.9412 - val_loss: 0.2072
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8930 - loss: 0.2869 - val_accuracy: 0.9412 - val_loss: 0.2039
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9064 - loss: 0.2840 - val_accuracy: 0.9412 - val_loss: 0.2017
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8896 - loss: 0.2822 - val_accuracy: 0.9412 - val_loss: 0.1991
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8896 - loss: 0.2780 - val_accuracy: 0.9412 - val_loss: 0.1942
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8997 - loss: 0.2756 - val_accuracy: 0.9412 - val_loss: 0.1913
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8997 - loss: 0.2725 - val_accuracy: 0.9412 - val_loss: 0.1868
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9030 - loss: 0.2690 - val_accuracy: 0.9412 - val_loss: 0.1840
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9030 - loss: 0.2662 - val_accuracy: 0.9412 - val_loss: 0.1817
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9030 - loss: 0.2632 - val_accuracy: 0.9412 - val_loss: 0.1790
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9064 - loss: 0.2604 - val_accuracy: 0.9412 - val_loss: 0.1755
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9030 - loss: 0.2573 - val_accuracy: 0.9412 - val_loss: 0.1714
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9030 - loss: 0.2546 - val_accuracy: 0.9412 - val_loss: 0.1682
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9030 - loss: 0.2514 - val_accuracy: 0.9412 - val_loss: 0.1647
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9097 - loss: 0.2484 - val_accuracy: 0.9412 - val_loss: 0.1613
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9130 - loss: 0.2454 - val_accuracy: 0.9412 - val_loss: 0.1586
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9130 - loss: 0.2420 - val_accuracy: 0.9412 - val_loss: 0.1549
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9064 - loss: 0.2403 - val_accuracy: 0.9412 - val_loss: 0.1508
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9164 - loss: 0.2366 - val_accuracy: 0.9412 - val_loss: 0.1494
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9097 - loss: 0.2345 - val_accuracy: 0.9412 - val_loss: 0.1452
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9164 - loss: 0.2322 - val_accuracy: 0.9412 - val_loss: 0.1436
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9130 - loss: 0.2286 - val_accuracy: 0.9706 - val_loss: 0.1404
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9197 - loss: 0.2257 - val_accuracy: 0.9706 - val_loss: 0.1371
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9231 - loss: 0.2234 - val_accuracy: 0.9706 - val_loss: 0.1346
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9197 - loss: 0.2206 - val_accuracy: 0.9706 - val_loss: 0.1316
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9231 - loss: 0.2175 - val_accuracy: 0.9706 - val_loss: 0.1297
11/11 - 0s - 4ms/step - accuracy: 0.9279 - loss: 0.2065

In [98]:
model_logit_false.predict(scaled_penguins_x)

11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

array([[8.95105839e-01, 1.04887411e-01, 6.70874897e-06],
       [7.06314296e-02, 8.99139643e-01, 3.02289203e-02],
       [7.86704183e-01, 2.13157609e-01, 1.38232921e-04],
       [1.04339642e-06, 1.78738753e-03, 9.98211503e-01],
       [8.23158860e-01, 1.76732257e-01, 1.08799322e-04],
       [2.44996950e-01, 7.50822902e-01, 4.18018224e-03],
       [6.14204228e-01, 3.85446638e-01, 3.49090464e-04],
       [6.37400763e-06, 3.96108022e-03, 9.96032536e-01],
       [1.93274978e-08, 1.07932981e-04, 9.99891996e-01],
       [3.04788027e-05, 1.44197242e-02, 9.85549867e-01],
       [4.80771065e-01, 5.15277922e-01, 3.95102520e-03],
       [8.94829810e-01, 1.05145164e-01, 2.51023303e-05],
       [6.78352594e-01, 3.21529090e-01, 1.18270800e-04],
       [8.19864511e-01, 1.80112258e-01, 2.31468493e-05],
       [3.20538044e-01, 6.77724063e-01, 1.73791882e-03],
       [8.46126974e-01, 1.53848246e-01, 2.47191037e-05],
       [8.96443129e-01, 1.03549331e-01, 7.59658269e-06],
       [1.22250322e-06, 1.77134771e-03, 9.98227417e-01],
       [8.66088033e-01, 1.33902684e-01, 9.28046211e-06],
       [1.77703246e-01, 8.14345181e-01, 7.95158464e-03],
       [7.30399966e-01, 2.69289076e-01, 3.10952950e-04],
       [8.65684211e-01, 1.34246320e-01, 6.94172631e-05],
       [8.23748112e-02, 8.75858724e-01, 4.17664386e-02],
       [1.09920471e-07, 4.46769060e-04, 9.99553144e-01],
       [8.78222287e-01, 1.21770218e-01, 7.52070218e-06],
       [8.83624673e-01, 1.16367191e-01, 8.10195070e-06],
       [2.06870610e-07, 6.64129329e-04, 9.99335587e-01],
       [4.07012671e-01, 5.90599835e-01, 2.38755695e-03],
       [4.97602182e-09, 4.01912039e-05, 9.99959826e-01],
       [4.07875091e-01, 5.90118706e-01, 2.00615730e-03],
       [6.71003227e-06, 5.98673942e-03, 9.94006515e-01],
       [1.34943202e-01, 8.53771389e-01, 1.12854186e-02],
       [6.97526455e-01, 3.02100956e-01, 3.72594019e-04],
       [5.67726016e-01, 4.31717277e-01, 5.56749699e-04],
       [2.10974514e-01, 7.74463475e-01, 1.45620089e-02],
       [5.57066739e-01, 4.42299545e-01, 6.33763906e-04],
       [6.45665277e-04, 6.64306208e-02, 9.32923675e-01],
       [4.72976787e-08, 3.30446870e-04, 9.99669552e-01],
       [8.81815434e-01, 1.18174836e-01, 9.75365492e-06],
       [8.93271744e-01, 1.06715351e-01, 1.28639513e-05],
       [9.12816465e-01, 8.71804282e-02, 3.10340783e-06],
       [8.66777420e-01, 1.33210406e-01, 1.20528412e-05],
       [1.59651484e-06, 1.40761165e-03, 9.98590767e-01],
       [6.98267911e-07, 1.13788224e-03, 9.98861432e-01],
       [8.93875837e-01, 1.06096685e-01, 2.75370003e-05],
       [7.57859647e-01, 2.42018804e-01, 1.21634585e-04],
       [4.76858169e-01, 5.22138894e-01, 1.00296130e-03],
       [8.64340544e-01, 1.35609984e-01, 4.94409178e-05],
       [8.94590259e-01, 1.05383962e-01, 2.56941421e-05],
       [1.38822168e-01, 8.29748988e-01, 3.14287879e-02],
       [7.87027717e-01, 2.12916359e-01, 5.59293439e-05],
       [2.33483931e-07, 6.06686226e-04, 9.99393106e-01],
       [3.49938955e-06, 3.96885816e-03, 9.96027708e-01],
       [8.88296843e-01, 1.11656554e-01, 4.66255806e-05],
       [8.03237677e-01, 1.96748957e-01, 1.32875075e-05],
       [3.16881014e-05, 9.87510383e-03, 9.90093291e-01],
       [8.76541555e-01, 1.23451822e-01, 6.54295036e-06],
       [7.92142332e-01, 2.07769424e-01, 8.82723107e-05],
       [2.14605809e-08, 1.19134420e-04, 9.99880910e-01],
       [5.86062932e-09, 8.13714505e-05, 9.99918580e-01],
       [6.11558437e-01, 3.88167113e-01, 2.74396181e-04],
       [3.53908181e-01, 6.42963052e-01, 3.12872906e-03],
       [3.85275036e-01, 6.12410128e-01, 2.31476291e-03],
       [8.69331658e-01, 1.30661026e-01, 7.40645419e-06],
       [8.89585018e-01, 1.10373661e-01, 4.13772759e-05],
       [2.63546437e-01, 7.34359324e-01, 2.09424365e-03],
       [6.70698047e-01, 3.28961730e-01, 3.40163300e-04],
       [8.36364904e-07, 1.77813263e-03, 9.98220980e-01],
       [8.33165109e-01, 1.66813880e-01, 2.09791797e-05],
       [7.38865495e-01, 2.61052251e-01, 8.22674410e-05],
       [8.78044248e-01, 1.21948950e-01, 6.84159022e-06],
       [8.93219769e-01, 1.06750973e-01, 2.93343237e-05],
       [2.19796362e-07, 5.48812735e-04, 9.99450982e-01],
       [2.59431392e-01, 7.34554231e-01, 6.01440622e-03],
       [1.63445088e-06, 2.31317477e-03, 9.97685194e-01],
       [3.30302055e-06, 3.54938582e-03, 9.96447265e-01],
       [8.92587721e-01, 1.07381098e-01, 3.11658514e-05],
       [8.91533494e-01, 1.08442098e-01, 2.44124094e-05],
       [8.89327824e-01, 1.10629775e-01, 4.23798738e-05],
       [8.13288207e-05, 1.93537809e-02, 9.80564892e-01],
       [8.90832484e-01, 1.09161131e-01, 6.40127610e-06],
       [8.66703093e-01, 1.33242682e-01, 5.42131020e-05],
       [1.96136225e-05, 9.74984840e-03, 9.90230501e-01],
       [7.82194197e-01, 2.17769250e-01, 3.65127598e-05],
       [7.11566389e-01, 2.88266420e-01, 1.67185804e-04],
       [5.29986277e-10, 1.36944345e-05, 9.99986291e-01],
       [8.95623565e-01, 1.04353212e-01, 2.32275452e-05],
       [3.48439738e-02, 8.18071783e-01, 1.47084221e-01],
       [6.14745950e-04, 7.95130432e-02, 9.19872224e-01],
       [2.92164856e-07, 7.85847718e-04, 9.99213934e-01],
       [9.63591162e-08, 4.53747372e-04, 9.99546111e-01],
       [5.71043015e-01, 4.28155720e-01, 8.01195274e-04],
       [7.18331158e-01, 2.81296104e-01, 3.72777751e-04],
       [8.19365144e-01, 1.80519149e-01, 1.15631330e-04],
       [7.81038046e-01, 2.18790099e-01, 1.71891705e-04],
       [9.12324250e-01, 8.76718760e-02, 3.94843482e-06],
       [7.87833393e-01, 2.12010711e-01, 1.55944435e-04],
       [1.62974757e-07, 5.50479803e-04, 9.99449432e-01],
       [7.65975952e-01, 2.33835131e-01, 1.88912716e-04],
       [8.59241962e-01, 1.40722364e-01, 3.57310892e-05],
       [8.51338327e-01, 1.48651078e-01, 1.05271147e-05],
       [3.72288913e-01, 6.23389661e-01, 4.32137679e-03],
       [1.10489435e-01, 8.57830167e-01, 3.16804275e-02],
       [8.07468235e-01, 1.92491040e-01, 4.07146472e-05],
       [2.50449807e-06, 1.92737288e-03, 9.98070180e-01],
       [8.63811731e-01, 1.36175394e-01, 1.29025557e-05],
       [1.63719264e-07, 4.34025744e-04, 9.99565899e-01],
       [5.35314712e-07, 8.61564418e-04, 9.99137878e-01],
       [8.79654169e-01, 1.20338961e-01, 6.94364462e-06],
       [1.18535227e-05, 4.97624325e-03, 9.95011926e-01],
       [9.00926828e-01, 9.90662277e-02, 7.01899035e-06],
       [1.61190405e-01, 8.11701298e-01, 2.71083247e-02],
       [2.66899973e-01, 7.23456204e-01, 9.64382291e-03],
       [6.57231867e-05, 1.46521050e-02, 9.85282123e-01],
       [5.64078491e-08, 2.45074421e-04, 9.99754965e-01],
       [5.96745622e-07, 1.16156240e-03, 9.98837888e-01],
       [8.28065574e-01, 1.71914592e-01, 1.98460330e-05],
       [1.08084782e-06, 1.65540993e-03, 9.98343468e-01],
       [4.49760020e-01, 5.48898697e-01, 1.34134421e-03],
       [5.19188781e-08, 2.16393775e-04, 9.99783576e-01],
       [8.88621867e-01, 1.11332953e-01, 4.52470231e-05],
       [3.21365462e-07, 4.91281564e-04, 9.99508381e-01],
       [5.52122295e-01, 4.47227776e-01, 6.49941037e-04],
       [8.90746891e-01, 1.09216034e-01, 3.71110364e-05],
       [8.85609865e-01, 1.14330620e-01, 5.95745150e-05],
       [1.17426567e-01, 8.61129284e-01, 2.14442089e-02],
       [9.02097166e-01, 9.78908092e-02, 1.20790546e-05],
       [8.78532350e-01, 1.21443540e-01, 2.40873742e-05],
       [7.17716694e-01, 2.81943768e-01, 3.39555496e-04],
       [9.85711290e-10, 1.91584204e-05, 9.99980807e-01],
       [8.85972381e-01, 1.14016175e-01, 1.14528902e-05],
       [8.94810081e-01, 1.05164759e-01, 2.51502279e-05],
       [5.50761399e-07, 8.13162245e-04, 9.99186218e-01],
       [7.86786199e-01, 2.13154107e-01, 5.97666622e-05],
       [9.10782158e-01, 8.92140195e-02, 3.82344524e-06],
       [9.10652280e-01, 8.93433467e-02, 4.39787846e-06],
       [5.87805914e-07, 1.45905570e-03, 9.98540401e-01],
       [6.04621649e-01, 3.94670278e-01, 7.08018837e-04],
       [5.14667690e-01, 4.84419674e-01, 9.12559917e-04],
       [7.99458086e-01, 2.00489059e-01, 5.28595956e-05],
       [8.02778959e-01, 1.97122037e-01, 9.90300832e-05],
       [7.60895205e-08, 2.68675358e-04, 9.99731243e-01],
       [9.06182051e-01, 9.38100070e-02, 7.83233099e-06],
       [1.30001232e-01, 8.64607334e-01, 5.39146969e-03],
       [3.22585583e-06, 3.61736445e-03, 9.96379435e-01],
       [4.90603447e-01, 5.09065747e-01, 3.30791343e-04],
       [2.63458946e-06, 3.46042519e-03, 9.96536970e-01],
       [9.89808664e-02, 8.86529326e-01, 1.44897802e-02],
       [2.97882906e-07, 6.06788439e-04, 9.99392867e-01],
       [3.41719158e-07, 8.16729909e-04, 9.99182880e-01],
       [6.11069663e-06, 3.83038027e-03, 9.96163607e-01],
       [1.55116613e-08, 8.91977324e-05, 9.99910831e-01],
       [8.47466648e-01, 1.52448446e-01, 8.48117343e-05],
       [6.59851611e-01, 3.39731336e-01, 4.17005620e-04],
       [1.94233095e-07, 4.53025365e-04, 9.99546707e-01],
       [1.31158347e-04, 3.34766880e-02, 9.66392219e-01],
       [5.54465601e-07, 7.71651219e-04, 9.99227762e-01],
       [8.60386789e-01, 1.39594987e-01, 1.81168944e-05],
       [2.76039609e-05, 7.86738377e-03, 9.92105007e-01],
       [1.25590188e-04, 2.13476662e-02, 9.78526711e-01],
       [7.27523267e-01, 2.72137314e-01, 3.39463819e-04],
       [3.48672241e-01, 6.48370743e-01, 2.95699970e-03],
       [3.78568202e-01, 6.19782209e-01, 1.64954807e-03],
       [6.08392991e-02, 8.60808730e-01, 7.83519745e-02],
       [3.67762073e-06, 3.99559969e-03, 9.96000707e-01],
       [7.12854444e-07, 8.88476148e-04, 9.99110758e-01],
       [1.31015008e-06, 2.22563138e-03, 9.97772992e-01],
       [2.10158069e-05, 9.65340529e-03, 9.90325570e-01],
       [1.92619353e-07, 3.99008510e-04, 9.99600828e-01],
       [6.77328467e-01, 3.22552353e-01, 1.19211567e-04],
       [8.94124687e-01, 1.05848417e-01, 2.68816912e-05],
       [2.09478799e-06, 2.98872800e-03, 9.97009218e-01],
       [4.39178735e-01, 5.58866680e-01, 1.95461279e-03],
       [7.90903568e-01, 2.09058642e-01, 3.78336299e-05],
       [2.32662499e-01, 7.62113273e-01, 5.22419298e-03],
       [3.12087655e-01, 6.86118305e-01, 1.79401378e-03],
       [7.95861721e-01, 2.03933820e-01, 2.04441851e-04],
       [8.99400890e-01, 1.00590982e-01, 8.18772696e-06],
       [7.22020388e-01, 2.77839452e-01, 1.40245873e-04],
       [8.01380396e-01, 1.98595852e-01, 2.37417244e-05],
       [3.43237013e-01, 6.55116558e-01, 1.64638332e-03],
       [7.27762520e-01, 2.71981686e-01, 2.55797058e-04],
       [3.72513787e-05, 1.44555327e-02, 9.85507250e-01],
       [2.88356781e-01, 7.08517969e-01, 3.12527618e-03],
       [8.19672763e-01, 1.80189177e-01, 1.38030213e-04],
       [1.53749337e-04, 2.71140244e-02, 9.72732186e-01],
       [2.21806502e-07, 6.87876891e-04, 9.99311924e-01],
       [8.03303838e-01, 1.96667045e-01, 2.90880998e-05],
       [5.34861207e-01, 4.64352548e-01, 7.86296267e-04],
       [8.84906530e-01, 1.15056731e-01, 3.66667264e-05],
       [4.73902225e-01, 5.24645507e-01, 1.45225937e-03],
       [5.53280830e-01, 4.44628090e-01, 2.09106389e-03],
       [8.70164101e-08, 2.72075180e-04, 9.99727786e-01],
       [4.17510659e-01, 5.80710471e-01, 1.77881855e-03],
       [4.39266387e-07, 6.10716059e-04, 9.99388814e-01],
       [7.08152533e-01, 2.91611195e-01, 2.36290274e-04],
       [9.10509527e-01, 8.94855484e-02, 4.85561213e-06],
       [8.94602299e-01, 1.05371967e-01, 2.56641451e-05],
       [9.24379790e-08, 3.05292138e-04, 9.99694586e-01],
       [7.66812563e-01, 2.33120427e-01, 6.70382651e-05],
       [7.19289375e-08, 3.93882219e-04, 9.99606073e-01],
       [8.03053975e-01, 1.96843103e-01, 1.02881553e-04],
       [5.83463550e-01, 4.16379184e-01, 1.57258633e-04],
       [8.59297037e-01, 1.40650004e-01, 5.30083526e-05],
       [6.17813349e-01, 3.81450802e-01, 7.35832728e-04],
       [4.76232964e-09, 4.38116804e-05, 9.99956131e-01],
       [1.04140738e-10, 6.43220665e-06, 9.99993563e-01],
       [6.03773032e-08, 2.08391895e-04, 9.99791563e-01],
       [3.55518848e-01, 6.36264026e-01, 8.21712334e-03],
       [8.93588543e-01, 1.06383160e-01, 2.83111513e-05],
       [5.71625233e-01, 4.26917255e-01, 1.45756989e-03],
       [6.27695655e-08, 2.99419858e-04, 9.99700546e-01],
       [2.43507702e-06, 1.74033409e-03, 9.98257339e-01],
       [8.98542643e-01, 1.01439975e-01, 1.73779590e-05],
       [8.85764062e-01, 1.14177264e-01, 5.87512477e-05],
       [1.95562214e-01, 7.95557737e-01, 8.88009090e-03],
       [8.98816943e-01, 1.01177767e-01, 5.41044164e-06],
       [1.26396369e-08, 1.14586706e-04, 9.99885440e-01],
       [8.90239716e-01, 1.09721340e-01, 3.89211491e-05],
       [5.77569962e-01, 4.21743572e-01, 6.86456042e-04],
       [6.93908215e-01, 3.05754483e-01, 3.37240635e-04],
       [5.67254305e-01, 4.32483703e-01, 2.61935493e-04],
       [3.19937289e-01, 6.75452113e-01, 4.61059529e-03],
       [2.31805615e-07, 5.19452791e-04, 9.99480307e-01],
       [7.60925293e-01, 2.39026591e-01, 4.80913332e-05],
       [1.18016521e-06, 2.10274989e-03, 9.97896075e-01],
       [4.56245388e-08, 1.71309497e-04, 9.99828696e-01],
       [5.66333830e-01, 4.32421297e-01, 1.24488072e-03],
       [7.65560471e-05, 1.52232666e-02, 9.84700203e-01],
       [8.81682456e-01, 1.18311375e-01, 6.15905401e-06],
       [8.20888579e-01, 1.79001331e-01, 1.10066598e-04],
       [2.28819990e-05, 1.22666722e-02, 9.87710416e-01],
       [8.65689218e-01, 1.34268463e-01, 4.22884041e-05],
       [2.95300379e-06, 1.96701312e-03, 9.98030007e-01],
       [7.28754401e-01, 2.70989627e-01, 2.56007217e-04],
       [2.37556836e-08, 1.07989399e-04, 9.99891996e-01],
       [5.10608517e-02, 8.83911312e-01, 6.50278851e-02],
       [7.66791761e-01, 2.33171344e-01, 3.69174559e-05],
       [2.53031701e-01, 7.42903590e-01, 4.06469684e-03],
       [5.12831939e-05, 1.18066613e-02, 9.88142073e-01],
       [2.50720739e-01, 7.40429819e-01, 8.84940010e-03],
       [8.33185911e-01, 1.66797191e-01, 1.69087234e-05],
       [7.80370470e-08, 2.52716942e-04, 9.99747217e-01],
       [1.66298628e-06, 2.20397441e-03, 9.97794390e-01],
       [5.17763681e-08, 2.41399845e-04, 9.99758661e-01],
       [8.97179246e-01, 1.02800854e-01, 1.99185670e-05],
       [8.13995540e-01, 1.85975507e-01, 2.90451917e-05],
       [8.53682637e-01, 1.46309555e-01, 7.78659614e-06],
       [5.17523149e-05, 1.80442668e-02, 9.81903970e-01],
       [1.18949327e-04, 2.75780875e-02, 9.72302973e-01],
       [2.97626794e-08, 1.55637099e-04, 9.99844313e-01],
       [7.40341723e-01, 2.59597659e-01, 6.05075656e-05],
       [2.03718391e-05, 1.24947084e-02, 9.87484872e-01],
       [8.41235042e-01, 1.58742040e-01, 2.29745619e-05],
       [8.76816452e-01, 1.23169735e-01, 1.37732968e-05],
       [3.18297170e-05, 9.48324334e-03, 9.90484953e-01],
       [8.89349043e-01, 1.10608630e-01, 4.22962548e-05],
       [8.45595300e-01, 1.54388234e-01, 1.65151469e-05],
       [8.98185134e-01, 1.01796925e-01, 1.80141051e-05],
       [9.00511503e-01, 9.94825140e-02, 5.87340401e-06],
       [6.96343601e-01, 3.03489447e-01, 1.67056874e-04],
       [5.39527446e-06, 3.88124329e-03, 9.96113420e-01],
       [8.25863302e-01, 1.74032673e-01, 1.04043858e-04],
       [3.69266391e-01, 6.29405022e-01, 1.32856308e-03],
       [8.23471129e-01, 1.76518798e-01, 1.01121832e-05],
       [7.98605197e-06, 4.26121429e-03, 9.95730817e-01],
       [3.57627124e-01, 6.39464438e-01, 2.90851505e-03],
       [2.43907675e-06, 3.02552688e-03, 9.96971965e-01],
       [2.74128274e-06, 3.12665082e-03, 9.96870577e-01],
       [3.50513687e-07, 8.16963497e-04, 9.99182642e-01],
       [1.00233182e-01, 8.63539755e-01, 3.62271294e-02],
       [3.02152621e-05, 1.27813378e-02, 9.87188399e-01],
       [4.68523979e-01, 5.31129301e-01, 3.46784364e-04],
       [2.90284097e-01, 7.03764021e-01, 5.95185906e-03],
       [4.30921644e-01, 5.67775130e-01, 1.30332576e-03],
       [8.45370741e-05, 2.46606991e-02, 9.75254774e-01],
       [4.20693510e-07, 6.90653629e-04, 9.99308825e-01],
       [8.38464141e-01, 1.61496401e-01, 3.94315939e-05],
       [4.30004370e-08, 2.56043539e-04, 9.99743998e-01],
       [2.00686273e-07, 5.55478968e-04, 9.99444306e-01],
       [9.99052361e-08, 2.90087482e-04, 9.99709785e-01],
       [6.59582019e-01, 3.40092778e-01, 3.25159752e-04],
       [8.91872346e-01, 1.08094290e-01, 3.33645476e-05],
       [6.69471383e-01, 3.30350697e-01, 1.77984577e-04],
       [8.66339803e-01, 1.33614942e-01, 4.52169079e-05],
       [8.90084624e-01, 1.09875880e-01, 3.94907875e-05],
       [5.96020473e-05, 2.08382271e-02, 9.79102075e-01],
       [8.72206390e-01, 1.27752051e-01, 4.16045841e-05],
       [4.30269637e-07, 1.02633098e-03, 9.98973250e-01],
       [7.68401742e-01, 2.31365368e-01, 2.32833219e-04],
       [9.05035913e-01, 9.49566811e-02, 7.35087178e-06],
       [2.37189415e-05, 9.25890449e-03, 9.90717351e-01],
       [2.63952771e-08, 1.90594074e-04, 9.99809444e-01],
       [9.09333408e-01, 9.06610936e-02, 5.54086228e-06],
       [8.88593435e-01, 1.11397736e-01, 8.75956903e-06],
       [1.42434448e-01, 8.47242236e-01, 1.03233494e-02],
       [4.71714827e-08, 1.58231196e-04, 9.99841690e-01],
       [1.54609248e-01, 8.31221044e-01, 1.41697284e-02],
       [5.71904004e-01, 4.27652866e-01, 4.43076104e-04],
       [4.76036578e-01, 5.22769332e-01, 1.19410676e-03],
       [9.79635388e-07, 1.39915664e-03, 9.98599946e-01],
       [9.04291749e-01, 9.57009718e-02, 7.32508715e-06],
       [7.93056250e-01, 2.06905350e-01, 3.83407678e-05],
       [2.80550267e-07, 5.34966763e-04, 9.99464810e-01],
       [2.90018278e-07, 5.92875935e-04, 9.99406934e-01],
       [1.31797180e-01, 8.34527373e-01, 3.36754732e-02],
       [1.55945290e-05, 8.93754419e-03, 9.91046846e-01],
       [2.67812517e-04, 3.58486287e-02, 9.63883519e-01],
       [9.08356547e-01, 9.16373506e-02, 6.13827751e-06],
       [9.08763051e-01, 9.12311077e-02, 5.90385025e-06],
       [2.47888494e-07, 6.54460338e-04, 9.99345243e-01],
       [2.64758946e-05, 8.31528753e-03, 9.91658270e-01],
       [8.92303944e-01, 1.07664123e-01, 3.20219697e-05],
       [8.37766274e-05, 2.84887254e-02, 9.71427560e-01],
       [5.27563512e-01, 4.71834958e-01, 6.01554464e-04],
       [3.25698275e-05, 1.45923235e-02, 9.85375166e-01],
       [2.61577547e-01, 7.35204339e-01, 3.21807805e-03],
       [1.23024313e-06, 1.97716174e-03, 9.98021603e-01],
       [1.84038311e-01, 8.06172907e-01, 9.78880003e-03],
       [2.14269022e-07, 4.44173347e-04, 9.99555528e-01],
       [8.86924267e-01, 1.13066874e-01, 8.89300372e-06],
       [1.74367688e-06, 2.30891863e-03, 9.97689366e-01],
       [8.91901553e-01, 1.08065203e-01, 3.32724085e-05],
       [8.66251886e-01, 1.33688673e-01, 5.94785524e-05],
       [4.87722161e-07, 1.26741233e-03, 9.98732150e-01],
       [7.47820973e-01, 2.51896411e-01, 2.82599445e-04],
       [7.77585059e-02, 8.99943888e-01, 2.22976059e-02],
       [8.88974905e-01, 1.11018747e-01, 6.38440815e-06],
       [5.26253862e-05, 1.37893716e-02, 9.86158013e-01],
       [8.90126169e-01, 1.09834433e-01, 3.93374212e-05],
       [7.45540142e-01, 2.54397869e-01, 6.20575229e-05],
       [1.02271944e-01, 8.70195508e-01, 2.75325067e-02],
       [9.00113046e-01, 9.98805389e-02, 6.40099188e-06]], dtype=float32)

In [99]:
penguins['species']

0         Adelie
1      Chinstrap
2         Adelie
3         Gentoo
4         Adelie
         ...
328       Gentoo
329       Adelie
330       Adelie
331    Chinstrap
332       Adelie
Name: species, Length: 333, dtype: object

In [100]:
penguins_y

array([0, 1, 0, 2, 0, 1, 1, 2, 2, 2, 0, 0, 1, 0, 1, 0, 0, 2, 0, 1, 0, 0, 1, 2, 0, 0, 2, 1, 2, 1, 2, 1, 0, 0, 1, 1, 2, 2, 0, 0, 0,
       0, 2, 2, 0, 0, 1, 0, 0, 1, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 0, 1, 0, 2, 0, 1, 0, 0, 2, 1, 2, 2, 0, 0, 0, 2, 0, 0,
       2, 0, 1, 2, 0, 1, 2, 2, 2, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 2, 0, 2, 2, 0, 2, 0, 1, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 1,
       0, 0, 1, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 1, 2, 1, 2, 1, 2, 2, 2, 2, 0, 0, 2, 2, 2, 0, 2, 2, 0, 1, 1, 1,
       2, 2, 2, 2, 2, 0, 0, 2, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 2, 1, 0, 2, 2, 0, 1, 0, 1, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 0, 1, 0, 0,
       2, 2, 2, 0, 0, 0, 2, 2, 0, 0, 1, 0, 2, 0, 1, 1, 1, 0, 2, 1, 2, 2, 0, 2, 0, 0, 2, 0, 2, 0, 2, 1, 0, 1, 2, 1, 0, 2, 2, 2, 0,
       0, 0, 2, 2, 2, 1, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 1, 1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0, 2,
       0, 2, 0, 0, 2, 2, 0, 0, 1, 2, 1, 0, 1, 2, 0, 0, 2, 2, 1, 2, 2, 0, 0, 2, 2, 0, 2, 1, 2, 1, 2, 1, 2, 0, 2, 0, 0, 2, 0, 1, 0,
       2, 0, 0, 1, 0], dtype=int8)